name: guru_booking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
